spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: PBattistella2024
    url: jdbc:postgresql://localhost:5432/project_db
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database: postgresql
springdoc:
  api-docs:
    path: /api-docs
  pathsToMatch:
    - /api/**
  swagger-ui:
    use-root-path: true

